// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Balivo.AppCenterClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Alerting webhook ping operation result
    /// </summary>
    public partial class AlertWebhookPingResult : AlertOperationResult
    {
        /// <summary>
        /// Initializes a new instance of the AlertWebhookPingResult class.
        /// </summary>
        public AlertWebhookPingResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AlertWebhookPingResult class.
        /// </summary>
        /// <param name="requestId">Unique request identifier for
        /// tracking</param>
        /// <param name="responseStatusCode">HTTP status code returned in
        /// response from calling webhook</param>
        /// <param name="responseReason">Reason returned in response from
        /// calling webhook</param>
        public AlertWebhookPingResult(string requestId, int responseStatusCode, string responseReason = default(string))
            : base(requestId)
        {
            ResponseStatusCode = responseStatusCode;
            ResponseReason = responseReason;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets HTTP status code returned in response from calling
        /// webhook
        /// </summary>
        [JsonProperty(PropertyName = "response_status_code")]
        public int ResponseStatusCode { get; set; }

        /// <summary>
        /// Gets or sets reason returned in response from calling webhook
        /// </summary>
        [JsonProperty(PropertyName = "response_reason")]
        public string ResponseReason { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public override void Validate()
        {
            base.Validate();
        }
    }
}
