// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Balivo.AppCenterClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The response of Multifactor login. This is a 30 day session token
    /// generated by apple.
    /// </summary>
    public partial class AppleMultifactorLoginResponse
    {
        /// <summary>
        /// Initializes a new instance of the AppleMultifactorLoginResponse
        /// class.
        /// </summary>
        public AppleMultifactorLoginResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AppleMultifactorLoginResponse
        /// class.
        /// </summary>
        /// <param name="username">the apple developer account.</param>
        /// <param name="cookie">The 30-day session Token generated by apple
        /// after successfully logging in with Multifactor
        /// authentication.</param>
        /// <param name="expires">The expiry date of the cookie generated by
        /// apple</param>
        public AppleMultifactorLoginResponse(string username = default(string), string cookie = default(string), string expires = default(string))
        {
            Username = username;
            Cookie = cookie;
            Expires = expires;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the apple developer account.
        /// </summary>
        [JsonProperty(PropertyName = "username")]
        public string Username { get; set; }

        /// <summary>
        /// Gets or sets the 30-day session Token generated by apple after
        /// successfully logging in with Multifactor authentication.
        /// </summary>
        [JsonProperty(PropertyName = "cookie")]
        public string Cookie { get; set; }

        /// <summary>
        /// Gets or sets the expiry date of the cookie generated by apple
        /// </summary>
        [JsonProperty(PropertyName = "expires")]
        public string Expires { get; set; }

    }
}
