// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Balivo.AppCenterClient.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AppRequest
    {
        /// <summary>
        /// Initializes a new instance of the AppRequest class.
        /// </summary>
        public AppRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AppRequest class.
        /// </summary>
        /// <param name="displayName">The descriptive name of the app. This can
        /// contain any characters</param>
        /// <param name="os">The OS the app will be running on. Possible values
        /// include: 'Android', 'iOS', 'macOS', 'Tizen', 'tvOS',
        /// 'Windows'</param>
        /// <param name="platform">The platform of the app. Possible values
        /// include: 'Java', 'Objective-C-Swift', 'UWP', 'Cordova',
        /// 'React-Native', 'Xamarin', 'Unity'</param>
        /// <param name="description">A short text describing the app</param>
        /// <param name="name">The name of the app used in URLs</param>
        public AppRequest(string displayName, string os, string platform, string description = default(string), string name = default(string))
        {
            Description = description;
            DisplayName = displayName;
            Name = name;
            Os = os;
            Platform = platform;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets a short text describing the app
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// Gets or sets the descriptive name of the app. This can contain any
        /// characters
        /// </summary>
        [JsonProperty(PropertyName = "display_name")]
        public string DisplayName { get; set; }

        /// <summary>
        /// Gets or sets the name of the app used in URLs
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the OS the app will be running on. Possible values
        /// include: 'Android', 'iOS', 'macOS', 'Tizen', 'tvOS', 'Windows'
        /// </summary>
        [JsonProperty(PropertyName = "os")]
        public string Os { get; set; }

        /// <summary>
        /// Gets or sets the platform of the app. Possible values include:
        /// 'Java', 'Objective-C-Swift', 'UWP', 'Cordova', 'React-Native',
        /// 'Xamarin', 'Unity'
        /// </summary>
        [JsonProperty(PropertyName = "platform")]
        public string Platform { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (DisplayName == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "DisplayName");
            }
            if (Os == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Os");
            }
            if (Platform == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Platform");
            }
        }
    }
}
