// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Balivo.AppCenterClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Usage section in the Billing Information
    /// </summary>
    public partial class BillingResourceUsage
    {
        /// <summary>
        /// Initializes a new instance of the BillingResourceUsage class.
        /// </summary>
        public BillingResourceUsage()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BillingResourceUsage class.
        /// </summary>
        public BillingResourceUsage(ServiceResourceUsage buildService = default(ServiceResourceUsage), ServiceResourceUsage pushService = default(ServiceResourceUsage), ServiceResourceUsage testService = default(ServiceResourceUsage))
        {
            BuildService = buildService;
            PushService = pushService;
            TestService = testService;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "buildService")]
        public ServiceResourceUsage BuildService { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pushService")]
        public ServiceResourceUsage PushService { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "testService")]
        public ServiceResourceUsage TestService { get; set; }

    }
}
