// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Balivo.AppCenterClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Billing plans for a given period
    /// </summary>
    public partial class BillingPeriod
    {
        /// <summary>
        /// Initializes a new instance of the BillingPeriod class.
        /// </summary>
        public BillingPeriod()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BillingPeriod class.
        /// </summary>
        /// <param name="startTime">Inclusive start of the period</param>
        /// <param name="endTime">Exclusive end of the period.</param>
        public BillingPeriod(string startTime = default(string), string endTime = default(string), BillingPlanSelection byAccount = default(BillingPlanSelection))
        {
            StartTime = startTime;
            EndTime = endTime;
            ByAccount = byAccount;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets inclusive start of the period
        /// </summary>
        [JsonProperty(PropertyName = "startTime")]
        public string StartTime { get; set; }

        /// <summary>
        /// Gets or sets exclusive end of the period.
        /// </summary>
        [JsonProperty(PropertyName = "endTime")]
        public string EndTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "byAccount")]
        public BillingPlanSelection ByAccount { get; set; }

    }
}
