// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Balivo.AppCenterClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Selection of a billing plan for one or more services
    /// </summary>
    public partial class BillingPlansSelection
    {
        /// <summary>
        /// Initializes a new instance of the BillingPlansSelection class.
        /// </summary>
        public BillingPlansSelection()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BillingPlansSelection class.
        /// </summary>
        public BillingPlansSelection(BillingPlanSelection buildService = default(BillingPlanSelection), BillingPlanSelection pushService = default(BillingPlanSelection), BillingPlanSelection testService = default(BillingPlanSelection))
        {
            BuildService = buildService;
            PushService = pushService;
            TestService = testService;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "buildService")]
        public BillingPlanSelection BuildService { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pushService")]
        public BillingPlanSelection PushService { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "testService")]
        public BillingPlanSelection TestService { get; set; }

    }
}
