// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Balivo.AppCenterClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CommitDetailsCommit
    {
        /// <summary>
        /// Initializes a new instance of the CommitDetailsCommit class.
        /// </summary>
        public CommitDetailsCommit()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CommitDetailsCommit class.
        /// </summary>
        /// <param name="message">Commit message</param>
        public CommitDetailsCommit(string message = default(string), CommitDetailsCommitAuthor author = default(CommitDetailsCommitAuthor))
        {
            Message = message;
            Author = author;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets commit message
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public string Message { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "author")]
        public CommitDetailsCommitAuthor Author { get; set; }

    }
}
