// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Balivo.AppCenterClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class CrashCounts
    {
        /// <summary>
        /// Initializes a new instance of the CrashCounts class.
        /// </summary>
        public CrashCounts()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CrashCounts class.
        /// </summary>
        /// <param name="count">total crash count</param>
        /// <param name="crashes">the total crash count for day</param>
        public CrashCounts(long? count = default(long?), IList<DateTimeCounts> crashes = default(IList<DateTimeCounts>))
        {
            Count = count;
            Crashes = crashes;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets total crash count
        /// </summary>
        [JsonProperty(PropertyName = "count")]
        public long? Count { get; set; }

        /// <summary>
        /// Gets or sets the total crash count for day
        /// </summary>
        [JsonProperty(PropertyName = "crashes")]
        public IList<DateTimeCounts> Crashes { get; set; }

    }
}
