// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Balivo.AppCenterClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CrashingAppDetail
    {
        /// <summary>
        /// Initializes a new instance of the CrashingAppDetail class.
        /// </summary>
        public CrashingAppDetail()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CrashingAppDetail class.
        /// </summary>
        /// <param name="appId">application identifier</param>
        /// <param name="appVersion">application version</param>
        /// <param name="crashGroupId">crash group identifier</param>
        public CrashingAppDetail(string appId = default(string), string appVersion = default(string), string crashGroupId = default(string))
        {
            AppId = appId;
            AppVersion = appVersion;
            CrashGroupId = crashGroupId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets application identifier
        /// </summary>
        [JsonProperty(PropertyName = "appId")]
        public string AppId { get; set; }

        /// <summary>
        /// Gets or sets application version
        /// </summary>
        [JsonProperty(PropertyName = "appVersion")]
        public string AppVersion { get; set; }

        /// <summary>
        /// Gets or sets crash group identifier
        /// </summary>
        [JsonProperty(PropertyName = "crashGroupId")]
        public string CrashGroupId { get; set; }

    }
}
