// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Balivo.AppCenterClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class DateTimeDecimalCounts
    {
        /// <summary>
        /// Initializes a new instance of the DateTimeDecimalCounts class.
        /// </summary>
        public DateTimeDecimalCounts()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DateTimeDecimalCounts class.
        /// </summary>
        /// <param name="datetime">the ISO 8601 datetime</param>
        /// <param name="count">decimal count of the object</param>
        public DateTimeDecimalCounts(string datetime = default(string), double? count = default(double?))
        {
            Datetime = datetime;
            Count = count;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the ISO 8601 datetime
        /// </summary>
        [JsonProperty(PropertyName = "datetime")]
        public string Datetime { get; set; }

        /// <summary>
        /// Gets or sets decimal count of the object
        /// </summary>
        [JsonProperty(PropertyName = "count")]
        public double? Count { get; set; }

    }
}
