// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Balivo.AppCenterClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class DeploymentInternal : Deployment
    {
        /// <summary>
        /// Initializes a new instance of the DeploymentInternal class.
        /// </summary>
        public DeploymentInternal()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DeploymentInternal class.
        /// </summary>
        public DeploymentInternal(string name, string key = default(string), CodePushRelease latestRelease = default(CodePushRelease), string id = default(string))
            : base(name, key, latestRelease)
        {
            Id = id;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public override void Validate()
        {
            base.Validate();
        }
    }
}
