// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Balivo.AppCenterClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class DistributionGroupWithoutIsLatest
    {
        /// <summary>
        /// Initializes a new instance of the DistributionGroupWithoutIsLatest
        /// class.
        /// </summary>
        public DistributionGroupWithoutIsLatest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DistributionGroupWithoutIsLatest
        /// class.
        /// </summary>
        /// <param name="id">ID identifying a unique distribution
        /// group.</param>
        /// <param name="name">A name identifying a unique distribution
        /// group.</param>
        public DistributionGroupWithoutIsLatest(string id = default(string), string name = default(string))
        {
            Id = id;
            Name = name;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets ID identifying a unique distribution group.
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets a name identifying a unique distribution group.
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

    }
}
