// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Balivo.AppCenterClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class DistributionGroupIdRequest
    {
        /// <summary>
        /// Initializes a new instance of the DistributionGroupIdRequest class.
        /// </summary>
        public DistributionGroupIdRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DistributionGroupIdRequest class.
        /// </summary>
        /// <param name="id">The id of the distribution group</param>
        public DistributionGroupIdRequest(System.Guid id)
        {
            Id = id;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the id of the distribution group
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid Id { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
