// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Balivo.AppCenterClient.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// App Center account details from GitHub billing
    /// </summary>
    public partial class GitHubBillingAccount
    {
        /// <summary>
        /// Initializes a new instance of the GitHubBillingAccount class.
        /// </summary>
        public GitHubBillingAccount()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GitHubBillingAccount class.
        /// </summary>
        /// <param name="id">The unique id (UUID) of the account</param>
        /// <param name="displayName">The account's display name</param>
        /// <param name="name">The unique name that used to identify the
        /// owner</param>
        /// <param name="type">The owner type. Can either be 'org' or 'user'.
        /// Possible values include: 'org', 'user'</param>
        public GitHubBillingAccount(string id, string displayName, string name, string type)
        {
            Id = id;
            DisplayName = displayName;
            Name = name;
            Type = type;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the unique id (UUID) of the account
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets the account's display name
        /// </summary>
        [JsonProperty(PropertyName = "display_name")]
        public string DisplayName { get; set; }

        /// <summary>
        /// Gets or sets the unique name that used to identify the owner
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the owner type. Can either be 'org' or 'user'.
        /// Possible values include: 'org', 'user'
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Id == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Id");
            }
            if (DisplayName == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "DisplayName");
            }
            if (Name == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Name");
            }
            if (Type == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Type");
            }
        }
    }
}
