// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Balivo.AppCenterClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class IntuneGroups
    {
        /// <summary>
        /// Initializes a new instance of the IntuneGroups class.
        /// </summary>
        public IntuneGroups()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the IntuneGroups class.
        /// </summary>
        /// <param name="odatacontext">context</param>
        /// <param name="value">categories for intune app</param>
        public IntuneGroups(string odatacontext = default(string), IList<IntuneGroupValue> value = default(IList<IntuneGroupValue>))
        {
            Odatacontext = odatacontext;
            Value = value;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets context
        /// </summary>
        [JsonProperty(PropertyName = "odata.context")]
        public string Odatacontext { get; set; }

        /// <summary>
        /// Gets or sets categories for intune app
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public IList<IntuneGroupValue> Value { get; set; }

    }
}
