// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Balivo.AppCenterClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Language
    {
        /// <summary>
        /// Initializes a new instance of the Language class.
        /// </summary>
        public Language()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Language class.
        /// </summary>
        /// <param name="languageName">language's name</param>
        /// <param name="count">count current of language</param>
        /// <param name="previousCount">count of previous lanugage</param>
        public Language(string languageName = default(string), long? count = default(long?), long? previousCount = default(long?))
        {
            LanguageName = languageName;
            Count = count;
            PreviousCount = previousCount;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets language's name
        /// </summary>
        [JsonProperty(PropertyName = "language_name")]
        public string LanguageName { get; set; }

        /// <summary>
        /// Gets or sets count current of language
        /// </summary>
        [JsonProperty(PropertyName = "count")]
        public long? Count { get; set; }

        /// <summary>
        /// Gets or sets count of previous lanugage
        /// </summary>
        [JsonProperty(PropertyName = "previous_count")]
        public long? PreviousCount { get; set; }

    }
}
