// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Balivo.AppCenterClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Languages
    {
        /// <summary>
        /// Initializes a new instance of the Languages class.
        /// </summary>
        public Languages()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Languages class.
        /// </summary>
        public Languages(long? total = default(long?), IList<Language> languagesProperty = default(IList<Language>))
        {
            Total = total;
            LanguagesProperty = languagesProperty;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "total")]
        public long? Total { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "languages")]
        public IList<Language> LanguagesProperty { get; set; }

    }
}
