// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Balivo.AppCenterClient.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Notification definition object
    /// </summary>
    public partial class NotificationDefinition
    {
        /// <summary>
        /// Initializes a new instance of the NotificationDefinition class.
        /// </summary>
        public NotificationDefinition()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NotificationDefinition class.
        /// </summary>
        public NotificationDefinition(NotificationContent notificationContent, NotificationTarget notificationTarget = default(NotificationTarget))
        {
            NotificationTarget = notificationTarget;
            NotificationContent = notificationContent;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "notification_target")]
        public NotificationTarget NotificationTarget { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "notification_content")]
        public NotificationContent NotificationContent { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (NotificationContent == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "NotificationContent");
            }
            if (NotificationContent != null)
            {
                NotificationContent.Validate();
            }
        }
    }
}
