// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Balivo.AppCenterClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class OrganizationUserPatchRequest
    {
        /// <summary>
        /// Initializes a new instance of the OrganizationUserPatchRequest
        /// class.
        /// </summary>
        public OrganizationUserPatchRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the OrganizationUserPatchRequest
        /// class.
        /// </summary>
        /// <param name="role">The user's role in the organizatiion. Possible
        /// values include: 'admin', 'collaborator'</param>
        public OrganizationUserPatchRequest(string role = default(string))
        {
            Role = role;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the user's role in the organizatiion. Possible values
        /// include: 'admin', 'collaborator'
        /// </summary>
        [JsonProperty(PropertyName = "role")]
        public string Role { get; set; }

    }
}
