// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Balivo.AppCenterClient.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The information for a single iOS device
    /// </summary>
    public partial class PublishDevicesResponse
    {
        /// <summary>
        /// Initializes a new instance of the PublishDevicesResponse class.
        /// </summary>
        public PublishDevicesResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PublishDevicesResponse class.
        /// </summary>
        /// <param name="profilesZipBase64">The updated provisioning profiles
        /// zip base64 encoded.</param>
        /// <param name="profileFileName">The file name for the provisioning
        /// profile.</param>
        public PublishDevicesResponse(string profilesZipBase64, string profileFileName = default(string))
        {
            ProfileFileName = profileFileName;
            ProfilesZipBase64 = profilesZipBase64;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the file name for the provisioning profile.
        /// </summary>
        [JsonProperty(PropertyName = "profile_file_name")]
        public string ProfileFileName { get; set; }

        /// <summary>
        /// Gets or sets the updated provisioning profiles zip base64 encoded.
        /// </summary>
        [JsonProperty(PropertyName = "profiles_zip_base64")]
        public string ProfilesZipBase64 { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (ProfilesZipBase64 == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "ProfilesZipBase64");
            }
        }
    }
}
