// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Balivo.AppCenterClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The response from the release creation API that just contains the
    /// created release's distinct id.
    /// </summary>
    public partial class ReleaseCreateResponse
    {
        /// <summary>
        /// Initializes a new instance of the ReleaseCreateResponse class.
        /// </summary>
        public ReleaseCreateResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ReleaseCreateResponse class.
        /// </summary>
        /// <param name="releaseDistinctId">The distinct ID of the
        /// release.</param>
        public ReleaseCreateResponse(double releaseDistinctId)
        {
            ReleaseDistinctId = releaseDistinctId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the distinct ID of the release.
        /// </summary>
        [JsonProperty(PropertyName = "release_distinct_id")]
        public double ReleaseDistinctId { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
