// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Balivo.AppCenterClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Response for updating a release
    /// </summary>
    public partial class ReleaseUpdateResponse
    {
        /// <summary>
        /// Initializes a new instance of the ReleaseUpdateResponse class.
        /// </summary>
        public ReleaseUpdateResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ReleaseUpdateResponse class.
        /// </summary>
        public ReleaseUpdateResponse(bool? mandatoryUpdate = default(bool?), string releaseNotes = default(string), string provisioningStatusUrl = default(string), IList<ReleaseUpdateResponseDestinationsItem> destinations = default(IList<ReleaseUpdateResponseDestinationsItem>))
        {
            MandatoryUpdate = mandatoryUpdate;
            ReleaseNotes = releaseNotes;
            ProvisioningStatusUrl = provisioningStatusUrl;
            Destinations = destinations;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mandatory_update")]
        public bool? MandatoryUpdate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "release_notes")]
        public string ReleaseNotes { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "provisioning_status_url")]
        public string ProvisioningStatusUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "destinations")]
        public IList<ReleaseUpdateResponseDestinationsItem> Destinations { get; set; }

    }
}
