// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Balivo.AppCenterClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// A response containing information about the uploaded release.
    /// </summary>
    public partial class ReleaseUploadEndResponse
    {
        /// <summary>
        /// Initializes a new instance of the ReleaseUploadEndResponse class.
        /// </summary>
        public ReleaseUploadEndResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ReleaseUploadEndResponse class.
        /// </summary>
        /// <param name="releaseId">The ID of the release.</param>
        /// <param name="releaseUrl">A URL to the new release. If upload was
        /// aborted will be null.</param>
        public ReleaseUploadEndResponse(double? releaseId = default(double?), string releaseUrl = default(string))
        {
            ReleaseId = releaseId;
            ReleaseUrl = releaseUrl;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the ID of the release.
        /// </summary>
        [JsonProperty(PropertyName = "release_id")]
        public double? ReleaseId { get; set; }

        /// <summary>
        /// Gets or sets a URL to the new release. If upload was aborted will
        /// be null.
        /// </summary>
        [JsonProperty(PropertyName = "release_url")]
        public string ReleaseUrl { get; set; }

    }
}
