// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Balivo.AppCenterClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The source repository
    /// </summary>
    public partial class SourceRepository
    {
        /// <summary>
        /// Initializes a new instance of the SourceRepository class.
        /// </summary>
        public SourceRepository()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SourceRepository class.
        /// </summary>
        /// <param name="name">The repository name</param>
        /// <param name="cloneUrl">URL used to clone the repository</param>
        public SourceRepository(string name = default(string), object cloneUrl = default(object))
        {
            Name = name;
            CloneUrl = cloneUrl;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the repository name
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets URL used to clone the repository
        /// </summary>
        [JsonProperty(PropertyName = "clone_url")]
        public object CloneUrl { get; set; }

    }
}
