// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Balivo.AppCenterClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class TestReportFeaturesItem
    {
        /// <summary>
        /// Initializes a new instance of the TestReportFeaturesItem class.
        /// </summary>
        public TestReportFeaturesItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TestReportFeaturesItem class.
        /// </summary>
        public TestReportFeaturesItem(string name = default(string), IList<TestReportFeaturesItemTestsItem> tests = default(IList<TestReportFeaturesItemTestsItem>), double? failed = default(double?), double? skipped = default(double?), double? peakMemory = default(double?), double? peakDuration = default(double?))
        {
            Name = name;
            Tests = tests;
            Failed = failed;
            Skipped = skipped;
            PeakMemory = peakMemory;
            PeakDuration = peakDuration;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tests")]
        public IList<TestReportFeaturesItemTestsItem> Tests { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "failed")]
        public double? Failed { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "skipped")]
        public double? Skipped { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "peakMemory")]
        public double? PeakMemory { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "peakDuration")]
        public double? PeakDuration { get; set; }

    }
}
