// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Balivo.AppCenterClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TesterAppWithReleaseResponse
    {
        /// <summary>
        /// Initializes a new instance of the TesterAppWithReleaseResponse
        /// class.
        /// </summary>
        public TesterAppWithReleaseResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TesterAppWithReleaseResponse
        /// class.
        /// </summary>
        /// <param name="id">The unique ID (UUID) of the app</param>
        /// <param name="name">The app's name.</param>
        /// <param name="displayName">The app's display name.</param>
        /// <param name="description">The description of the app</param>
        /// <param name="iconUrl">A URL to the app's icon.</param>
        /// <param name="os">The app's os.</param>
        /// <param name="owner">The information about the app's owner</param>
        public TesterAppWithReleaseResponse(string id = default(string), TesterAppRelease release = default(TesterAppRelease), string name = default(string), string displayName = default(string), string description = default(string), string iconUrl = default(string), string os = default(string), TesterAppWithReleaseResponseOwner owner = default(TesterAppWithReleaseResponseOwner))
        {
            Id = id;
            Release = release;
            Name = name;
            DisplayName = displayName;
            Description = description;
            IconUrl = iconUrl;
            Os = os;
            Owner = owner;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the unique ID (UUID) of the app
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "release")]
        public TesterAppRelease Release { get; set; }

        /// <summary>
        /// Gets or sets the app's name.
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the app's display name.
        /// </summary>
        [JsonProperty(PropertyName = "display_name")]
        public string DisplayName { get; set; }

        /// <summary>
        /// Gets or sets the description of the app
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// Gets or sets a URL to the app's icon.
        /// </summary>
        [JsonProperty(PropertyName = "icon_url")]
        public string IconUrl { get; set; }

        /// <summary>
        /// Gets or sets the app's os.
        /// </summary>
        [JsonProperty(PropertyName = "os")]
        public string Os { get; set; }

        /// <summary>
        /// Gets or sets the information about the app's owner
        /// </summary>
        [JsonProperty(PropertyName = "owner")]
        public TesterAppWithReleaseResponseOwner Owner { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Release != null)
            {
                Release.Validate();
            }
        }
    }
}
