// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Balivo.AppCenterClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class TestReportFeaturesItemTestsItemRunsItemStepsItem
    {
        /// <summary>
        /// Initializes a new instance of the
        /// TestReportFeaturesItemTestsItemRunsItemStepsItem class.
        /// </summary>
        public TestReportFeaturesItemTestsItemRunsItemStepsItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// TestReportFeaturesItemTestsItemRunsItemStepsItem class.
        /// </summary>
        public TestReportFeaturesItemTestsItemRunsItemStepsItem(string stepName = default(string), string id = default(string), IList<TestReportFeaturesItemTestsItemRunsItemStepsItemStepExecutionsItem> stepExecutions = default(IList<TestReportFeaturesItemTestsItemRunsItemStepsItemStepExecutionsItem>), double? failed = default(double?), double? skipped = default(double?), string stepReportUrl = default(string))
        {
            StepName = stepName;
            Id = id;
            StepExecutions = stepExecutions;
            Failed = failed;
            Skipped = skipped;
            StepReportUrl = stepReportUrl;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "stepName")]
        public string StepName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "stepExecutions")]
        public IList<TestReportFeaturesItemTestsItemRunsItemStepsItemStepExecutionsItem> StepExecutions { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "failed")]
        public double? Failed { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "skipped")]
        public double? Skipped { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "step_report_url")]
        public string StepReportUrl { get; set; }

    }
}
