// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Balivo.AppCenterClient.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class UserNameAvailabilityResponse
    {
        /// <summary>
        /// Initializes a new instance of the UserNameAvailabilityResponse
        /// class.
        /// </summary>
        public UserNameAvailabilityResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the UserNameAvailabilityResponse
        /// class.
        /// </summary>
        /// <param name="available">The availability status of the requested
        /// user name</param>
        /// <param name="name">The requested user name</param>
        public UserNameAvailabilityResponse(bool available, string name)
        {
            Available = available;
            Name = name;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the availability status of the requested user name
        /// </summary>
        [JsonProperty(PropertyName = "available")]
        public bool Available { get; set; }

        /// <summary>
        /// Gets or sets the requested user name
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Name == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Name");
            }
        }
    }
}
