// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Balivo.AppCenterClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class VersionDiagnostics
    {
        /// <summary>
        /// Initializes a new instance of the VersionDiagnostics class.
        /// </summary>
        public VersionDiagnostics()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the VersionDiagnostics class.
        /// </summary>
        /// <param name="version">version</param>
        /// <param name="count">version count</param>
        /// <param name="previousCount">the count of previous time range of the
        /// version</param>
        public VersionDiagnostics(string version = default(string), long? count = default(long?), long? previousCount = default(long?))
        {
            Version = version;
            Count = count;
            PreviousCount = previousCount;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets version
        /// </summary>
        [JsonProperty(PropertyName = "version")]
        public string Version { get; set; }

        /// <summary>
        /// Gets or sets version count
        /// </summary>
        [JsonProperty(PropertyName = "count")]
        public long? Count { get; set; }

        /// <summary>
        /// Gets or sets the count of previous time range of the version
        /// </summary>
        [JsonProperty(PropertyName = "previous_count")]
        public long? PreviousCount { get; set; }

    }
}
