// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Balivo.AppCenterClient.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class XcodeScheme
    {
        /// <summary>
        /// Initializes a new instance of the XcodeScheme class.
        /// </summary>
        public XcodeScheme()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the XcodeScheme class.
        /// </summary>
        /// <param name="name">Scheme name</param>
        /// <param name="hasTestAction">Does scheme have a test action?</param>
        /// <param name="archiveConfiguration">Build configuration set in
        /// Archive action</param>
        public XcodeScheme(string name, bool hasTestAction, string archiveConfiguration = default(string), XcodeArchiveProject archiveProject = default(XcodeArchiveProject))
        {
            Name = name;
            HasTestAction = hasTestAction;
            ArchiveConfiguration = archiveConfiguration;
            ArchiveProject = archiveProject;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets scheme name
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets does scheme have a test action?
        /// </summary>
        [JsonProperty(PropertyName = "hasTestAction")]
        public bool HasTestAction { get; set; }

        /// <summary>
        /// Gets or sets build configuration set in Archive action
        /// </summary>
        [JsonProperty(PropertyName = "archiveConfiguration")]
        public string ArchiveConfiguration { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "archiveProject")]
        public XcodeArchiveProject ArchiveProject { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Name == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Name");
            }
            if (ArchiveProject != null)
            {
                ArchiveProject.Validate();
            }
        }
    }
}
