// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Balivo.AppCenterClient
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for App.
    /// </summary>
    public static partial class AppExtensions
    {
            /// <summary>
            /// **Warning, this operation is not reversible.**
            ///
            /// A successful call to this API will permanently stop ingesting any logs
            /// received via SDK by app_id, and cannot be restored. We advise caution when
            /// using this API, it is designed to permanently disable an app_id.
            ///
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='ownerName'>
            /// The name of the owner
            /// </param>
            /// <param name='appName'>
            /// The name of the application
            /// </param>
            public static string BlockLogs(this IApp operations, string ownerName, string appName)
            {
                return operations.BlockLogsAsync(ownerName, appName).GetAwaiter().GetResult();
            }

            /// <summary>
            /// **Warning, this operation is not reversible.**
            ///
            /// A successful call to this API will permanently stop ingesting any logs
            /// received via SDK by app_id, and cannot be restored. We advise caution when
            /// using this API, it is designed to permanently disable an app_id.
            ///
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='ownerName'>
            /// The name of the owner
            /// </param>
            /// <param name='appName'>
            /// The name of the application
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<string> BlockLogsAsync(this IApp operations, string ownerName, string appName, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.BlockLogsWithHttpMessagesAsync(ownerName, appName, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
