// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Balivo.AppCenterClient
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for BugTracker.
    /// </summary>
    public static partial class BugTrackerExtensions
    {
            /// <summary>
            /// Get project issue related to a crash group
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='crashGroupId'>
            /// CrashGroup Id
            /// </param>
            /// <param name='ownerName'>
            /// The name of the owner
            /// </param>
            /// <param name='appName'>
            /// The name of the application
            /// </param>
            public static BugTrackerIssueResult GetRepoIssueFromCrash(this IBugTracker operations, string crashGroupId, string ownerName, string appName)
            {
                return operations.GetRepoIssueFromCrashAsync(crashGroupId, ownerName, appName).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get project issue related to a crash group
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='crashGroupId'>
            /// CrashGroup Id
            /// </param>
            /// <param name='ownerName'>
            /// The name of the owner
            /// </param>
            /// <param name='appName'>
            /// The name of the application
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<BugTrackerIssueResult> GetRepoIssueFromCrashAsync(this IBugTracker operations, string crashGroupId, string ownerName, string appName, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetRepoIssueFromCrashWithHttpMessagesAsync(crashGroupId, ownerName, appName, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Get bug tracker settings for a particular app
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='ownerName'>
            /// The name of the owner
            /// </param>
            /// <param name='appName'>
            /// The name of the application
            /// </param>
            public static AlertingBugtracker GetSettings(this IBugTracker operations, string ownerName, string appName)
            {
                return operations.GetSettingsAsync(ownerName, appName).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get bug tracker settings for a particular app
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='ownerName'>
            /// The name of the owner
            /// </param>
            /// <param name='appName'>
            /// The name of the application
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<AlertingBugtracker> GetSettingsAsync(this IBugTracker operations, string ownerName, string appName, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetSettingsWithHttpMessagesAsync(ownerName, appName, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
