// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Balivo.AppCenterClient
{
    using Models;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for Commits.
    /// </summary>
    public static partial class CommitsExtensions
    {
            /// <summary>
            /// Returns commit information for a batch of shas
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='hashes'>
            /// A collection of commit SHAs comma-delimited
            /// </param>
            /// <param name='ownerName'>
            /// The name of the owner
            /// </param>
            /// <param name='appName'>
            /// The name of the application
            /// </param>
            public static IList<CommitDetails> ListByShaList(this ICommits operations, IList<string> hashes, string ownerName, string appName)
            {
                return operations.ListByShaListAsync(hashes, ownerName, appName).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Returns commit information for a batch of shas
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='hashes'>
            /// A collection of commit SHAs comma-delimited
            /// </param>
            /// <param name='ownerName'>
            /// The name of the owner
            /// </param>
            /// <param name='appName'>
            /// The name of the application
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<CommitDetails>> ListByShaListAsync(this ICommits operations, IList<string> hashes, string ownerName, string appName, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ListByShaListWithHttpMessagesAsync(hashes, ownerName, appName, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
